apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    service: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cart
  template:
    metadata:
      labels:
        service: cart
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: cart
        image: {{ .Values.image.repo }}/rs-cart:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'curl http://cart:8080/health | grep -q true'
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
      {{- with .Values.cart.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cart.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cart.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.secret }}
      {{- if .Values.secret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.secret.name }}
      {{- end }}
      {{- end }}
